-- ---------------------------------------------------------------------------
-- Convert Users ID and FKs to UUID safely preserving Foreign Key links
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'users' AND column_name = 'id' AND data_type != 'uuid'
    ) THEN
        -- 1. Drop existing FK constraint
        ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS fk_ur_user;
        ALTER TABLE users ALTER COLUMN id DROP DEFAULT;

        -- 2. Add temporary new UUID column on users and generate UUIDs
        ALTER TABLE users ADD COLUMN IF NOT EXISTS uuid_id UUID DEFAULT gen_random_uuid();
        UPDATE users SET uuid_id = gen_random_uuid() WHERE uuid_id IS NULL;

        -- 3. Add temporary new UUID column on user_roles and populate from users via join
        ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS new_user_id UUID;
        UPDATE user_roles ur SET new_user_id = u.uuid_id FROM users u WHERE ur.user_id = u.id;

        -- 4. Swap columns in users
        ALTER TABLE users DROP COLUMN id;
        ALTER TABLE users RENAME COLUMN uuid_id TO id;
        ALTER TABLE users ADD PRIMARY KEY (id);

        -- 5. Swap columns in user_roles
        ALTER TABLE user_roles DROP COLUMN user_id;
        ALTER TABLE user_roles RENAME COLUMN new_user_id TO user_id;
        ALTER TABLE user_roles ALTER COLUMN user_id SET NOT NULL;
        ALTER TABLE user_roles ADD PRIMARY KEY (user_id, role_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_ur_user'
    ) THEN
        ALTER TABLE user_roles ADD CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;
END $$;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS reference_system VARCHAR(50),
    ADD COLUMN IF NOT EXISTS reference_value VARCHAR(255),
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS domain_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_date TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_modified_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS last_modified_date TIMESTAMP WITH TIME ZONE;

UPDATE users SET email = user_name || '@example.com' WHERE email IS NULL;

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL;

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_email') THEN
        ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_users_user_name ON users(user_name);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS revinfo (
    rev INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE IF NOT EXISTS users_aud (
    id UUID NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT,
    user_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(50),
    reference_system VARCHAR(50),
    reference_value VARCHAR(255),
    password_hash VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    version BIGINT,
    domain_version BIGINT,
    created_by VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_users_aud PRIMARY KEY (id, rev)
);

ALTER TABLE users_aud
    ADD COLUMN IF NOT EXISTS reference_system VARCHAR(50),
    ADD COLUMN IF NOT EXISTS reference_value VARCHAR(255);

CREATE SCHEMA IF NOT EXISTS audit;

-- ---------------------------------------------------------------------------
-- Hibernate Envers: Revision Info Table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.revinfo (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          BIGINT        NOT NULL,
    actor       TEXT          NULL,
    tenant_id   TEXT          NULL,
    extras_json TEXT          NULL
);

-- ---------------------------------------------------------------------------
-- Bedrock Audit Log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.audit_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action              TEXT          NOT NULL,
    resource_type       TEXT          NOT NULL,
    created_date        TIMESTAMP(6)  NOT NULL,
    arguments           TEXT          NULL,
    class_name          TEXT          NULL,
    client_ip           TEXT          NULL,
    description         TEXT          NULL,
    error_message       TEXT          NULL,
    error_stack_trace   TEXT          NULL,
    execution_time_ms   BIGINT        NULL,
    method_name         TEXT          NULL,
    resource_id         TEXT          NULL,
    result              TEXT          NULL,
    session_id          TEXT          NULL,
    status              VARCHAR(50)   NULL CHECK (status IN ('SUCCESS', 'FAILURE', 'PARTIAL_SUCCESS', 'CANCELLED', 'IN_PROGRESS')),
    user_agent          TEXT          NULL,
    user_id             TEXT          NULL,
    username            TEXT          NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_username     ON audit.audit_log (username);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_date ON audit.audit_log (created_date);
CREATE INDEX IF NOT EXISTS idx_audit_log_resource     ON audit.audit_log (resource_type, resource_id);

CREATE TABLE IF NOT EXISTS audit.audit_event_metadata (
    audit_event_id  BIGINT        NOT NULL,
    metadata_key    TEXT          NOT NULL,
    metadata_value  TEXT          NULL,
    PRIMARY KEY (audit_event_id, metadata_key),
    FOREIGN KEY (audit_event_id) REFERENCES audit.audit_log(id)
);

CREATE TABLE IF NOT EXISTS audit.audit_event_tags (
    service_audit_event_id  BIGINT        NOT NULL,
    tag                     TEXT          NULL,
    FOREIGN KEY (service_audit_event_id) REFERENCES audit.audit_log(id)
);

-- ---------------------------------------------------------------------------
-- Spring Modulith: Transactional Outbox Event Publication Tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_publication (
    id UUID PRIMARY KEY,
    event_type VARCHAR(500),
    listener_id VARCHAR(500),
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP(6) WITH TIME ZONE,
    completion_date TIMESTAMP(6) WITH TIME ZONE,
    last_resubmission_date TIMESTAMP(6) WITH TIME ZONE,
    completion_attempts INTEGER,
    status VARCHAR(255) CHECK (status IN ('PUBLISHED','PROCESSING','COMPLETED','FAILED','RESUBMITTED'))
);

CREATE TABLE IF NOT EXISTS event_publication_archive (
    id UUID PRIMARY KEY,
    event_type VARCHAR(500),
    listener_id VARCHAR(500),
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP(6) WITH TIME ZONE,
    completion_date TIMESTAMP(6) WITH TIME ZONE,
    last_resubmission_date TIMESTAMP(6) WITH TIME ZONE,
    completion_attempts INTEGER,
    status VARCHAR(255) CHECK (status IN ('PUBLISHED','PROCESSING','COMPLETED','FAILED','RESUBMITTED'))
);
