ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS domain_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_date TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_modified_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS last_modified_date TIMESTAMP WITH TIME ZONE;

UPDATE users SET email = user_name || '@example.com' WHERE email IS NULL;

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL,
    ADD CONSTRAINT uq_users_email UNIQUE (email);

CREATE INDEX IF NOT EXISTS idx_users_user_name ON users(user_name);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS revinfo (
    rev INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE IF NOT EXISTS users_aud (
    id BIGINT NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT,
    user_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(50),
    password_hash VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    version BIGINT,
    domain_version BIGINT,
    created_by VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_users_aud PRIMARY KEY (id, rev)
);


CREATE SCHEMA IF NOT EXISTS audit;

-- ---------------------------------------------------------------------------
-- Hibernate Envers: Revision Info Table (Length limitations removed)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.revinfo (
                                             id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             ts          BIGINT        NOT NULL,
                                             actor       TEXT          NULL,
                                             tenant_id   TEXT          NULL,
                                             extras_json TEXT          NULL
);

-- ---------------------------------------------------------------------------
-- Bedrock Audit Log (All string length limitations removed as requested)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.audit_log (
                                               id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               action              TEXT          NOT NULL,
                                               resource_type       TEXT          NOT NULL,
                                               created_date        TIMESTAMP(6)  NOT NULL,
    arguments           TEXT          NULL,
    class_name          TEXT          NULL,
    client_ip           TEXT          NULL,
    description         TEXT          NULL,
    error_message       TEXT          NULL,
    error_stack_trace   TEXT          NULL,
    execution_time_ms   BIGINT        NULL,
    method_name         TEXT          NULL,
    resource_id         TEXT          NULL,
    result              TEXT          NULL,
    session_id          TEXT          NULL,
    status              VARCHAR(50)   NULL CHECK (status IN ('SUCCESS', 'FAILURE', 'PARTIAL_SUCCESS', 'CANCELLED', 'IN_PROGRESS')),
    user_agent          TEXT          NULL,
    user_id             TEXT          NULL,
    username            TEXT          NULL
    );

CREATE INDEX IF NOT EXISTS idx_audit_log_username     ON audit.audit_log (username);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_date ON audit.audit_log (created_date);
CREATE INDEX IF NOT EXISTS idx_audit_log_resource     ON audit.audit_log (resource_type, resource_id);

CREATE TABLE IF NOT EXISTS audit.audit_event_metadata (
                                                          audit_event_id  BIGINT        NOT NULL,
                                                          metadata_key    TEXT          NOT NULL,
                                                          metadata_value  TEXT          NULL,
                                                          PRIMARY KEY (audit_event_id, metadata_key),
    FOREIGN KEY (audit_event_id) REFERENCES audit.audit_log(id)
    );

CREATE TABLE IF NOT EXISTS audit.audit_event_tags (
                                                      service_audit_event_id  BIGINT        NOT NULL,
                                                      tag                     TEXT          NULL,
                                                      FOREIGN KEY (service_audit_event_id) REFERENCES audit.audit_log(id)
    );
