CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_name VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone_number VARCHAR(50),
    reference_system VARCHAR(50),
    reference_value VARCHAR(255),
    status VARCHAR(20) DEFAULT 'INACTIVE' NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    domain_version BIGINT NOT NULL DEFAULT 0,
    password_temporary BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_user_name ON users(user_name);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ---------------------------------------------------------------------------
-- Hibernate Envers: Revision Info Table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS revinfo (
    rev INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE IF NOT EXISTS users_aud (
    id UUID NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT,
    user_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(50),
    reference_system VARCHAR(50),
    reference_value VARCHAR(255),
    status VARCHAR(20),
    password_hash VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    version BIGINT,
    domain_version BIGINT,
    password_temporary BOOLEAN,
    created_by VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_users_aud PRIMARY KEY (id, rev)
);

CREATE SCHEMA IF NOT EXISTS audit;

-- ---------------------------------------------------------------------------
-- Hibernate Envers: Revision Info Table (audit schema)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.revinfo (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          BIGINT        NOT NULL,
    actor       TEXT          NULL,
    tenant_id   TEXT          NULL,
    extras_json TEXT          NULL
);

-- ---------------------------------------------------------------------------
-- Bedrock Audit Log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit.audit_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action              TEXT          NOT NULL,
    resource_type       TEXT          NOT NULL,
    created_date        TIMESTAMP(6)  NOT NULL,
    arguments           TEXT          NULL,
    class_name          TEXT          NULL,
    client_ip           TEXT          NULL,
    description         TEXT          NULL,
    error_message       TEXT          NULL,
    error_stack_trace   TEXT          NULL,
    execution_time_ms   BIGINT        NULL,
    method_name         TEXT          NULL,
    resource_id         TEXT          NULL,
    result              TEXT          NULL,
    session_id          TEXT          NULL,
    status              VARCHAR(50)   NULL CHECK (status IN ('SUCCESS', 'FAILURE', 'PARTIAL_SUCCESS', 'CANCELLED', 'IN_PROGRESS')),
    user_agent          TEXT          NULL,
    user_id             TEXT          NULL,
    username            TEXT          NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_username     ON audit.audit_log (username);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_date ON audit.audit_log (created_date);
CREATE INDEX IF NOT EXISTS idx_audit_log_resource     ON audit.audit_log (resource_type, resource_id);

CREATE TABLE IF NOT EXISTS audit.audit_event_metadata (
    audit_event_id  BIGINT        NOT NULL,
    metadata_key    TEXT          NOT NULL,
    metadata_value  TEXT          NULL,
    PRIMARY KEY (audit_event_id, metadata_key),
    FOREIGN KEY (audit_event_id) REFERENCES audit.audit_log(id)
);

CREATE TABLE IF NOT EXISTS audit.audit_event_tags (
    service_audit_event_id  BIGINT        NOT NULL,
    tag                     TEXT          NULL,
    FOREIGN KEY (service_audit_event_id) REFERENCES audit.audit_log(id)
);

-- ---------------------------------------------------------------------------
-- Spring Modulith: Transactional Outbox Event Publication Tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_publication (
    id UUID PRIMARY KEY,
    event_type VARCHAR(500),
    listener_id VARCHAR(500),
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP(6) WITH TIME ZONE,
    completion_date TIMESTAMP(6) WITH TIME ZONE,
    last_resubmission_date TIMESTAMP(6) WITH TIME ZONE,
    completion_attempts INTEGER,
    status VARCHAR(255) CHECK (status IN ('PUBLISHED','PROCESSING','COMPLETED','FAILED','RESUBMITTED'))
);

CREATE TABLE IF NOT EXISTS event_publication_archive (
    id UUID PRIMARY KEY,
    event_type VARCHAR(500),
    listener_id VARCHAR(500),
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP(6) WITH TIME ZONE,
    completion_date TIMESTAMP(6) WITH TIME ZONE,
    last_resubmission_date TIMESTAMP(6) WITH TIME ZONE,
    completion_attempts INTEGER,
    status VARCHAR(255) CHECK (status IN ('PUBLISHED','PROCESSING','COMPLETED','FAILED','RESUBMITTED'))
);
