ALTER TABLE users
    ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE,
    ADD COLUMN phone_number VARCHAR(50),
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN domain_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN created_date TIMESTAMP WITH TIME ZONE,
    ADD COLUMN last_modified_by VARCHAR(255),
    ADD COLUMN last_modified_date TIMESTAMP WITH TIME ZONE;

CREATE INDEX idx_users_user_name ON users(user_name);
CREATE INDEX idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS revinfo (
    rev INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE users_aud (
    id BIGINT NOT NULL,
    rev INT NOT NULL,
    revtype SMALLINT,
    user_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(50),
    password_hash VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    version BIGINT,
    domain_version BIGINT,
    created_by VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_users_aud PRIMARY KEY (id, rev)
);
