ALTER TABLE role ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE role_aud ADD COLUMN IF NOT EXISTS is_system BOOLEAN DEFAULT FALSE;

UPDATE role SET is_system = TRUE WHERE name IN ('SECURITY_ADMIN', 'ADMIN', 'USER', 'MANAGER', 'AUDITOR', 'SUPPORT');
