services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shared_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    volumes:
      - minio_data:/data

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "3310:3310"
    restart: unless-stopped
    volumes:
      - clamav_data:/var/lib/clamav

  libreoffice:
    image: ghcr.io/jodconverter/jodconverter-examples:rest
    container_name: libreoffice
    ports:
      - "8082:8080"
    restart: unless-stopped

volumes:
  rabbitmq_data:
  minio_data:
  clamav_data: