input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Drop repetitive internal OPA bundle polling requests
  if [requestUri] =~ /^\/internal\/authz\/bundle/ {
    drop { }
  }
}

output {
  # Unified Operational & Action Telemetry Stream
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bedrock-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
