package org.datamate.authz.client;

import com.datamate.bedrock.framework.common.logging.annotation.EnableLogger;
import com.datamate.bedrock.framework.common.logging.service.Logger;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
//import org.datamate.authz.api.policy.PolicyValidation;
import org.datamate.authz.api.policy.PolicyValidation;
import org.datamate.authz.model.policy.valueobject.RegoValidationError;
import org.datamate.authz.model.policy.valueobject.RegoValidationResult;
import org.springframework.http.*;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;

public class OpaPolicyValidator implements PolicyValidation {

    @EnableLogger
    Logger log;
    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;
    private final String opaPolicyBaseUrl;

    private static final int WRAPPER_LINE_OFFSET = 8;

    public OpaPolicyValidator(
            RestTemplate restTemplate,
            ObjectMapper objectMapper,
            String opaBaseUrl) {
        this.restTemplate = restTemplate;
        this.objectMapper = objectMapper;
        this.opaPolicyBaseUrl = opaBaseUrl + "/v1/policies/";
    }

    @Override
    public RegoValidationResult validate(String regoSnippet) {
        String policyId = "_validation_temp_policy";
        boolean isFullBundle = regoSnippet != null && regoSnippet.trim().startsWith("package app.authz.");
        
        String fullModule = buildTemporaryModule(policyId, regoSnippet, isFullBundle);
        String url = opaPolicyBaseUrl + policyId;

        try {
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.TEXT_PLAIN);
            HttpEntity<String> request = new HttpEntity<>(fullModule, headers);

            ResponseEntity<String> response = restTemplate.exchange(
                    url, HttpMethod.PUT, request, String.class);

            if (response.getStatusCode().is2xxSuccessful()) {
                return RegoValidationResult.success();
            }

            return RegoValidationResult.failure(List.of(
                    new RegoValidationError(0, 0, "Unexpected OPA response: " + response.getStatusCode())
            ));

        } catch (HttpClientErrorException.BadRequest e) {
            String errorBody = e.getResponseBodyAsString();
            return parseErrorsWithOffset(errorBody, isFullBundle ? 0 : WRAPPER_LINE_OFFSET);
        } catch (RestClientException e) {
            log.error("Failed to connect to OPA sidecar for validation", e);
            throw new RuntimeException("OPA Sidecar unavailable for validation", e);
        } finally {
            cleanupTemporaryPolicy(url);
        }
    }

    private String buildTemporaryModule(String policyId, String snippet, boolean isFullBundle) {
        if (isFullBundle) {
            // It's a full bundle generated by the compiler.
            // We just rewrite the package statement so it doesn't conflict with the active live bundle!
            return snippet.replaceFirst("(?m)^package\\s+[\\w\\.]+", "package " + policyId);
        }

        // It's a custom Rego snippet from the UI.
        // We wrap it in the exact boilerplate the compiler uses so that we can catch duplicate
        // defaults (e.g. multiple `default allow_rule`) BEFORE it ever reaches the compiler!
        String cleanSnippet = snippet;
        if (cleanSnippet != null && cleanSnippet.trim().startsWith("package ")) {
            cleanSnippet = cleanSnippet.replaceFirst("(?m)^package\\s+[\\w\\.]+", "");
        }
        
        return "package " + policyId + "\n"
                + "\n"
                + "import rego.v1\n"
                + "\n"
                + "default allow := false\n"
                + "default allow_rule := false\n"
                + "default deny_rule := false\n"
                + "\n"
                + cleanSnippet + "\n"
                + "\n"
                + "allow if {\n"
                + "    allow_rule\n"
                + "    not deny_rule\n"
                + "}\n";
    }

    private RegoValidationResult parseErrorsWithOffset(String responseBody, int offset) {
        List<RegoValidationError> validationErrors = new ArrayList<>();
        try {
            JsonNode root = objectMapper.readTree(responseBody);
            JsonNode errorsNode = root.get("errors");

            if (errorsNode != null && errorsNode.isArray()) {
                for (JsonNode errorNode : errorsNode) {
                    String message = errorNode.has("message")
                            ? errorNode.get("message").asText()
                            : "Unknown syntax error";

                    int line = 0;
                    int column = 0;
                    JsonNode location = errorNode.get("location");
                    if (location != null) {
                        line = Math.max(0, location.path("row").asInt(0) - offset);
                        column = location.path("col").asInt(0);
                    }

                    validationErrors.add(new RegoValidationError(line, column, message));
                }
            }

            if (validationErrors.isEmpty()) {
                String message = root.has("message")
                        ? root.get("message").asText()
                        : "Rego syntax error";
                validationErrors.add(new RegoValidationError(0, 0, message));
            }
        } catch (Exception e) {
            log.error("Failed to parse OPA error response: {}", responseBody, e);
            validationErrors.add(new RegoValidationError(0, 0, "Unparseable error from OPA"));
        }
        return RegoValidationResult.failure(validationErrors);
    }

    private void cleanupTemporaryPolicy(String url) {
        try {
            restTemplate.delete(url);
        } catch (HttpClientErrorException.NotFound e) {
            // Expected
        } catch (RestClientException e) {
            log.warn("Failed to cleanup temporary OPA policy at {}. Non-fatal.", url, e);
        }
    }
}
