# 1. OPA Agent Configuration
services:
  pharmacy_api:
    url: http://host.docker.internal:8083
    credentials:
      bearer:
        token: "my-dev-secret"

bundles:
  pharmacy_bundle:
    service: pharmacy_api
    resource: /internal/authz/bundle/pharmacy
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

default_authorization_decision: /app/authz/pharmacy/allow

# 2. Java Application Configuration
evaluation_url: http://localhost:8183/v1/data/app/authz/pharmacy/allow
