CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS audit.revinfo (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          BIGINT        NOT NULL,
    actor       TEXT          NULL,
    tenant_id   TEXT          NULL,
    extras_json TEXT          NULL
);
